framework:
    messenger:
        failure_transport: failed

        transports:
            sync: 'sync://'
            async:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: messenger
                    group: symfony
            failed: 'doctrine://default?queue_name=failed'
            # scheduler_default is auto-registered by symfony/scheduler

        routing:
            'App\Messenger\Message\NotifyUnreadMessageMessage': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                sync: 'sync://'
