---
name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0

      - name: Build Docker images
        uses: docker/bake-action@v7.2.0
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.ci.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        run: docker compose -f compose.yaml -f compose.ci.yaml up --wait --no-build

      - name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost/login

      - name: Check HTTPS reachability
        run: curl -v --insecure --fail-with-body https://localhost/login

      - name: Check Mercure reachability
        run: curl -vI --insecure --fail-with-body https://localhost/.well-known/mercure?topic=test

      - name: Create test database
        run: docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/console doctrine:database:create --if-not-exists

      - name: Run migrations
        run: docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/console doctrine:migrations:migrate --no-interaction

      - name: Load fixtures
        run: docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/console doctrine:fixtures:load --no-interaction

      - name: Run PHPUnit
        run: docker compose -f compose.yaml -f compose.ci.yaml exec -T php php bin/phpunit

      - name: Doctrine schema validator
        run: docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/console doctrine:schema:validate

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0

      - name: Build Docker image
        uses: docker/bake-action@v7.2.0
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.ci.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: PHP-CS-Fixer
        run: docker compose -f compose.yaml -f compose.ci.yaml run --rm --no-deps -e SKIP_DB_WAIT=1 php php vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: PHPStan
        run: docker compose -f compose.yaml -f compose.ci.yaml run --rm --no-deps -e SKIP_DB_WAIT=1 php php vendor/bin/phpstan analyse --memory-limit=256M

      - name: Lint Twig
        run: docker compose -f compose.yaml -f compose.ci.yaml run --rm --no-deps -e SKIP_DB_WAIT=1 php bin/console lint:twig templates/

      - name: Lint YAML
        run: docker compose -f compose.yaml -f compose.ci.yaml run --rm --no-deps -e SKIP_DB_WAIT=1 php bin/console lint:yaml config

      - name: Lint container
        run: docker compose -f compose.yaml -f compose.ci.yaml run --rm --no-deps -e SKIP_DB_WAIT=1 php bin/console lint:container
